php:
  build: ./php
  links:
    - redis
  volumes:
    - ../symfony:/var/www/html
redis:
  image: redis:2.8
nginx:
  build: ./nginx
  links:
    - php:php-fpm
  ports:
    - "80:80"
  volumes:
    - ../symfony:/var/www/html
